package com.opendroid.app.core.domain

/**
 * 8-State Room Task State Machine
 * Deterministic states surviving Android process death
 */
enum class TaskStatus {
    CREATED,
    ANALYZING,
    PLANNED,
    WAITING_CONFIRMATION,
    EXECUTING,
    VERIFYING,
    COMPLETED,
    FAILED
}

/**
 * Deterministic 4-Tier Pure Risk Level
 */
enum class RiskLevel {
    SAFE,
    CONFIRM,
    HIGH_RISK,
    BLOCKED
}

/**
 * Structured Tool Call Request generated by GBNF Grammar parser
 */
data class ToolCallRequest(
    val id: String,
    val name: String,
    val arguments: Map<String, Any?>
)

/**
 * Native execution and verification output
 */
data class ToolExecutionResult(
    val success: Boolean,
    val output: Map<String, Any?>? = null,
    val error: String? = null,
    val verificationPassed: Boolean = false,
    val verificationDetails: String? = null
)

/**
 * Structured model decision output
 */
sealed class StructuredModelDecision {
    data class ToolCall(
        val thought: String,
        val toolCall: ToolCallRequest
    ) : StructuredModelDecision()

    data class DirectResponse(
        val thought: String,
        val response: String
    ) : StructuredModelDecision()

    data class BlockedOrInvalid(
        val reason: String
    ) : StructuredModelDecision()
}

/**
 * Tool definition contract
 */
data class ToolParameter(
    val name: String,
    val type: String, // "string", "number", "boolean", "object"
    val description: String,
    val required: Boolean = true
)

data class ToolDefinition(
    val id: String,
    val name: String,
    val description: String,
    val riskTier: RiskLevel,
    val timeoutMs: Long,
    val parameters: List<ToolParameter>
)
